BallotMeasures/urls.py
from django.urls import path

from . import views

app_name = 'BallotMeasures'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('<int:topic_id>/like/<int:group_id>/', views.like, name='like'),
]

CheckYoSelf/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    # path('BallotMeasures/', include('BallotMeasures.urls')),
    path('ballotmeasures/', include('BallotMeasures.urls')),
    path('coffee/', include('Coffee.urls')),
    path('chemicals/', include('Chemicals.urls')),
    path('elements/', include('Elements.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('captcha/', include('captcha.urls')),
    path('tinymce/', include('tinymce.urls')),
]

Chemicals/urls.py
from django.urls import path

from . import views

app_name = 'Chemicals'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('<int:topic_id>/like/<int:group_id>/', views.like, name='like'),
]

Coffee/urls.py
from django.urls import path

from . import views

app_name = 'Coffee'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/result/', views.search_result, name='searchResult'),
    path('recipe/', views.recipe_home, name='recipeHome'),
    path('recipe/<int:recipe_id>/', views.recipe, name='recipe'),
    path('recipe/<int:recipe_id>/like', views.recipe_like, name='recipeLike'),
    path('recipe/<int:recipe_id>/comment', views.recipe_comment, name='recipeComment'),
    path('written/', views.written_home, name='writtenPieceHome'),
    path('written/<int:written_id>/', views.written, name='writtenPiece'),
    path('written/<int:written_id>/like', views.written_like, name='writtenPieceLike'),
    path('written/<int:written_id>/comment', views.written_comment, name='writtenPieceComment')
]

Elements/urls.py
from django.urls import path

from . import views

app_name = 'Elements'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:element_name>/', views.detail, name='detail')
]

BallotMeasures/models.py
from django.db import models


class Topic(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=600)

    def __str__(self):
        return self.title


class Group(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    poster = models.URLField(max_length=200)
    research = models.URLField(max_length=200)
    class_name = models.CharField(max_length=50, default="na")
    likes = models.IntegerField(default=0)

    def like(self):
        self.likes += 1
        self.save()

    def __str__(self):
        return self.class_name + ' ' + self.topic.title


class Student(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_initial = models.CharField(max_length=4)

    def __str__(self):
        return self.first_name + ' ' + self.last_initial

BallotMeasures/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import CaptchaForm
from .models import Topic, Group


def index(request):
    topic_list = Topic.objects.order_by('title')
    context = {'topic_list': topic_list}
    return render(request, 'BallotMeasures/index.html', context)


def detail(request, topic_id):
    topic = get_object_or_404(Topic, pk=topic_id)
    context = {'topic': topic, 'form': CaptchaForm()}
    return render(request, 'BallotMeasures/detail.html', context)


def like(request, topic_id, group_id):
    if request.POST:
        form = CaptchaForm(request.POST)

        if form.is_valid():
            get_object_or_404(Group, pk=group_id).like()

    return redirect('BallotMeasures:detail', topic_id=topic_id)

templates/BallotMeasures/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ topic.title }}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fuchsiaviciouskeygen.mitchelllong.repl.co/style.css">
</head>
<body class="mw-100 w-100">

{# Main nav for all pages #}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home' %}">Check Yo Self</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'Elements:index' %}">Elements</a>
        <a class="nav-item nav-link " href="{% url 'Coffee:index' %}">Coffee</a>
        <a class="nav-item nav-link active" href="{% url 'BallotMeasures:index' %}">Ballot Measures</a>
        <a class="nav-item nav-link" href="{% url 'Chemicals:index' %}">Controversial Chemicals</a>
    </div>
</nav>
<div class="p-4 extra-padding"></div>

<main class="mt-4 w-100">
    <div>
        <a href="{% url 'BallotMeasures:index' %}" class="btn btn-secondary float-left m-3 ml-5">Go Back</a>
    </div>

    <div class="container text-center m-auto w-100">
        <div class="jumbotron p-2">
            <h1 class="display-3">{{ topic.title }}</h1>
            <p>{{ topic.description }}</p>
            <div class="d-inline-block w-auto">
                <ul class="nav nav-pills">
                    {% for group in topic.group_set.all %}
                        <li class="nav-item">
                            <a class="nav-link{% if group == topic.group_set.first %} active{% endif %}"
                               data-toggle="pill"
                               href="#{{ group.class_name }}">{{ group.class_name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>


        <div class="tab-content">
            {% for group in topic.group_set.all %}
                <div class="tab-pane container {% if group == topic.group_set.first %}active{% else %}fade{% endif %}"
                     id="{{ group.class_name }}">
                    <ul class="my-2 justify-content-center list-group list-group-horizontal">
                        {% for student in group.student_set.all %}
                            <li class="list-group-item">{{ student }}</li>
                        {% endfor %}
                    </ul>

                    <img class="img-fluid rounded mb-5" src="{{ group.poster }}">

                    {# Upvotes #}
                    <div class="row w-25 mx-auto mb-3">
                        <div class="col-sm my-auto">
                            <p class="my-auto bg-success text-light d-inline-block rounded px-3 py-2">{{ group.likes }}
                                Upvotes</p>
                        </div>
                    </div>

                    {# Add Upvote #}
                    <form action="{% url 'BallotMeasures:like' topic.id group.id %}" method="post" id="form">
                        {% csrf_token %}
                        <div class="row mx-auto justify-content-center">
                            <div class="px-1 my-auto">
                                {{ form.captcha }}
                            </div>
                            <div class="px-1 my-auto">
                                <input type="submit" value="Add Upvote" class="btn btn-success btn-sm">
                            </div>
                        </div>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
</main>

{# Footer that goes on every page #}
<footer class="mt-5">
    <div class="container mt-5 mb-5">
        <a href="#" class="float-right"><p class="text-primary">Back To Top</p></a>
        <p class="m-3">Created by Mitchell L. and Scott S.</p>
        <p class="m-3">Created Using
            <a href="https://www.djangoproject.com/" target="_blank" class="d-inline">Django</a>
            and <a href="https://getbootstrap.com/" target="_blank" class="d-inline">Bootstrap</a>
        </p>
    </div>
</footer>

</body>
</html>

templates/BallotMeasures/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ballot Measures</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fuchsiaviciouskeygen.mitchelllong.repl.co/style.css">
</head>
<body>

{# Main nav for all pages #}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home' %}">Check Yo Self</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'Elements:index' %}">Elements</a>
        <a class="nav-item nav-link " href="{% url 'Coffee:index' %}">Coffee</a>
        <a class="nav-item nav-link active" href="{% url 'BallotMeasures:index' %}">Ballot Measures</a>
        <a class="nav-item nav-link" href="{% url 'Chemicals:index' %}">Controversial Chemicals</a>
    </div>
</nav>
<div class="p-4 extra-padding"></div>

<h1 class="jumbotron text-center">Ballot Measures</h1>

<main>
    <div>
        <a href="{% url 'home' %}" class="btn btn-secondary float-left m-3 ml-5">Go Back</a>
    </div>
    <div class="container">
        <div class="row">
            {% for topic in topic_list %}
                <div class="col-md-4">
                    <a class="text-black-50 text-decoration-none" href="{% url 'BallotMeasures:detail' topic.id %}">
                        <div class="card mb-4 shadow">
                            <div class="card-header"><h2 class="card-text">{{ topic.title }}</h2></div>
                            <div class="card-body">
                                <p class="card-text mb-3">{{ topic.description }}</p>
                                <a class="btn btn-primary d-block" href="{% url 'BallotMeasures:detail' topic.id %}">Read
                                    More</a>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</main>

{# Footer that goes on every page #}
<footer class="mt-5">
    <div class="container mt-5 mb-5">
        <a href="#" class="float-right"><p class="text-primary">Back To Top</p></a>
        <p class="m-3">Created by Mitchell L. and Scott S.</p>
        <p class="m-3">Created Using
            <a href="https://www.djangoproject.com/" target="_blank" class="d-inline">Django</a>
            and <a href="https://getbootstrap.com/" target="_blank" class="d-inline">Bootstrap</a>
        </p>
    </div>
</footer>

</body>
</html>