BallotMeasures/urls.py
from django.urls import path

from . import views

app_name = 'BallotMeasures'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('<int:topic_id>/like/<int:group_id>/', views.like, name='like'),
]

CheckYoSelf/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    # path('BallotMeasures/', include('BallotMeasures.urls')),
    path('ballotmeasures/', include('BallotMeasures.urls')),
    path('coffee/', include('Coffee.urls')),
    path('chemicals/', include('Chemicals.urls')),
    path('elements/', include('Elements.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('captcha/', include('captcha.urls')),
    path('tinymce/', include('tinymce.urls')),
]

Chemicals/urls.py
from django.urls import path

from . import views

app_name = 'Chemicals'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('<int:topic_id>/like/<int:group_id>/', views.like, name='like'),
]

Coffee/urls.py
from django.urls import path

from . import views

app_name = 'Coffee'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/result/', views.search_result, name='searchResult'),
    path('recipe/', views.recipe_home, name='recipeHome'),
    path('recipe/<int:recipe_id>/', views.recipe, name='recipe'),
    path('recipe/<int:recipe_id>/like', views.recipe_like, name='recipeLike'),
    path('recipe/<int:recipe_id>/comment', views.recipe_comment, name='recipeComment'),
    path('written/', views.written_home, name='writtenPieceHome'),
    path('written/<int:written_id>/', views.written, name='writtenPiece'),
    path('written/<int:written_id>/like', views.written_like, name='writtenPieceLike'),
    path('written/<int:written_id>/comment', views.written_comment, name='writtenPieceComment')
]

Elements/urls.py
from django.urls import path

from . import views

app_name = 'Elements'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:element_name>/', views.detail, name='detail')
]

Elements/models.py
from django.db import models
from tinymce.models import HTMLField


class Product(models.Model):
    element = models.CharField(max_length=50, unique=True)
    number = models.IntegerField(unique=True)
    author = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    body = HTMLField()

    def __str__(self):
        return self.element

Elements/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product


# Create your views here.
def index(request):
    element_list = Product.objects.order_by('number')
    return render(request, 'Elements/index.html', {'element_list': element_list})


def detail(request, element_name):
    obj = get_object_or_404(Product, element=element_name)
    return render(request, 'Elements/detail.html', {'element': obj})

templates/Elements/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ element.title }}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fuchsiaviciouskeygen.mitchelllong.repl.co/style.css">
</head>
<body class="mw-100 w-100">

{# Main nav for all pages #}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home' %}">Check Yo Self</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link active" href="{% url 'Elements:index' %}">Elements</a>
        <a class="nav-item nav-link" href="{% url 'Coffee:index' %}">Coffee</a>
        <a class="nav-item nav-link" href="{% url 'BallotMeasures:index' %}">Ballot Measures</a>
        <a class="nav-item nav-link" href="{% url 'Chemicals:index' %}">Controversial Chemicals</a>
    </div>
</nav>
<div class="p-4 extra-padding"></div>

<main class="mt-4 w-100 h-75">
    <div class="container text-center m-auto w-100">
        <div class="jumbotron p-2">
            <h1 class="display-3">{{ element.number }} - {{ element.element }}</h1>
            <h4>{{ element.author }}</h4>
        </div>

        <div class="my-4">{{ element.body|safe }}</div>

        <div>
            <img src="https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://checkyoself2020.herokuapp.com/elements/{{ element.element }}"
                 alt="qr code">
        </div>
    </div>
</main>

{# Footer that goes on every page #}
<footer class="mt-5">
    <div class="container mt-5 mb-5">
        <a href="#" class="float-right"><p class="text-primary">Back To Top</p></a>
        <p class="m-3">Created by Mitchell L. and Scott S.</p>
        <p class="m-3">Created Using
            <a href="https://www.djangoproject.com/" target="_blank" class="d-inline">Django</a>
            and <a href="https://getbootstrap.com/" target="_blank" class="d-inline">Bootstrap</a>
        </p>
    </div>
</footer>

</body>
</html>

templates/Elements/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Elements</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fuchsiaviciouskeygen.mitchelllong.repl.co/style.css">
</head>
<body>

{# Main nav for all pages #}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home' %}">Check Yo Self</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link active" href="{% url 'Elements:index' %}">Elements</a>
        <a class="nav-item nav-link" href="{% url 'Coffee:index' %}">Coffee</a>
        <a class="nav-item nav-link" href="{% url 'BallotMeasures:index' %}">Ballot Measures</a>
        <a class="nav-item nav-link" href="{% url 'Chemicals:index' %}">Controversial Chemicals</a>
    </div>
</nav>
<div class="p-4 extra-padding"></div>

<h1 class="jumbotron text-center">Elements</h1>

<main>
    <div class="container">
        <div class="row">
            {% for element in element_list %}
                <div class="col-md-4">
                    <a class="text-black-50 text-decoration-none" href="">
                        <div class="card mb-4 shadow">
                            <div class="card-header"><h2 class="card-text">{{ element.number }}
                                - {{ element.element }}</h2></div>
                            <div class="card-body">
                                <h4 class="card-subtitle mb-2">{{ element.author }}</h4>
                                <h6 class="card-text my-4">{{ element.type }}</h6>
                                <a class="btn btn-primary d-block" href="{% url 'Elements:detail' element.element %}">Read
                                    More</a>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</main>

{# Footer that goes on every page #}
<footer class="mt-5">
    <div class="container mt-5 mb-5">
        <a href="#" class="float-right"><p class="text-primary">Back To Top</p></a>
        <p class="m-3">Created by Mitchell L. and Scott S.</p>
        <p class="m-3">Created Using
            <a href="https://www.djangoproject.com/" target="_blank" class="d-inline">Django</a>
            and <a href="https://getbootstrap.com/" target="_blank" class="d-inline">Bootstrap</a>
        </p>
    </div>
</footer>

</body>
</html>