BallotMeasures/urls.py
from django.urls import path

from . import views

app_name = 'BallotMeasures'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('<int:topic_id>/like/<int:group_id>/', views.like, name='like'),
]

CheckYoSelf/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    # path('BallotMeasures/', include('BallotMeasures.urls')),
    path('ballotmeasures/', include('BallotMeasures.urls')),
    path('coffee/', include('Coffee.urls')),
    path('chemicals/', include('Chemicals.urls')),
    path('elements/', include('Elements.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('captcha/', include('captcha.urls')),
    path('tinymce/', include('tinymce.urls')),
]

Chemicals/urls.py
from django.urls import path

from . import views

app_name = 'Chemicals'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:topic_id>/', views.detail, name='detail'),
    path('<int:topic_id>/like/<int:group_id>/', views.like, name='like'),
]

Coffee/urls.py
from django.urls import path

from . import views

app_name = 'Coffee'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('search/result/', views.search_result, name='searchResult'),
    path('recipe/', views.recipe_home, name='recipeHome'),
    path('recipe/<int:recipe_id>/', views.recipe, name='recipe'),
    path('recipe/<int:recipe_id>/like', views.recipe_like, name='recipeLike'),
    path('recipe/<int:recipe_id>/comment', views.recipe_comment, name='recipeComment'),
    path('written/', views.written_home, name='writtenPieceHome'),
    path('written/<int:written_id>/', views.written, name='writtenPiece'),
    path('written/<int:written_id>/like', views.written_like, name='writtenPieceLike'),
    path('written/<int:written_id>/comment', views.written_comment, name='writtenPieceComment')
]

Elements/urls.py
from django.urls import path

from . import views

app_name = 'Elements'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:element_name>/', views.detail, name='detail')
]

Coffee/models.py
from django.db import models
from tinymce.models import HTMLField


class Recipe(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    likes = models.IntegerField(default=0)
    image = models.URLField(max_length=200)
    thumbnail = models.URLField(max_length=200)

    def like(self):
        self.likes += 1
        self.save()

    def __str__(self):
        return self.title


class RecipeComment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=50)
    body = models.CharField(max_length=200)

    def __str__(self):
        return 'Artwork Comment {} by {}'.format(self.body, self.author)


class WrittenPiece(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    text = HTMLField()
    likes = models.IntegerField(default=0)
    thumbnail = models.URLField(max_length=200)
    type = models.CharField(max_length=20, choices=[('Op-Ed', 'Op-Ed'), ('Historical Fiction', 'Historical Fiction')],
                            default="Op-Ed")

    def like(self):
        self.likes += 1
        self.save()

    def __str__(self):
        return self.title


class WrittenPieceComment(models.Model):
    written_piece = models.ForeignKey(WrittenPiece, on_delete=models.CASCADE, related_name='comments')
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=50)
    body = models.CharField(max_length=200)

    def __str__(self):
        return 'Written Piece Comment {} by {}'.format(self.body, self.author)

Coffee/forms.py
from captcha.fields import CaptchaField
from django import forms


class CaptchaForm(forms.Form):
    captcha = CaptchaField()


class CommentForm(forms.Form):
    captcha = CaptchaField()
    author = forms.CharField(max_length=100)
    comment = forms.CharField(max_length=500)


class SearchForm(forms.Form):
    text = forms.CharField(max_length=100)
    type = forms.ChoiceField(choices=[('w', 'Written Piece'), ('r', 'Recipe')])

Coffee/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from profanityfilter import ProfanityFilter

from .forms import CaptchaForm, CommentForm, SearchForm
from .models import Recipe, RecipeComment, WrittenPiece, WrittenPieceComment

pf = ProfanityFilter(extra_censor_list=open('Coffee/profanity_list.txt', 'r').read().split('\n'))


def index(request):
    return render(request, 'Coffee/index.html')


def recipe_home(request):
    recipe_list = Recipe.objects.order_by('title')
    return render(request, 'Coffee/recipe_home.html', {'recipe_list': recipe_list})


def recipe(request, recipe_id):
    obj = get_object_or_404(Recipe, pk=recipe_id)
    context = {'recipe': obj, 'likeForm': CaptchaForm(),
               'commentForm': CommentForm, 'comments_ordered': obj.comments.all().order_by('-timestamp')}
    return render(request, 'Coffee/recipe.html', context)


def recipe_like(request, recipe_id):
    if request.POST:
        form = CaptchaForm(request.POST)

        if form.is_valid():
            get_object_or_404(Recipe, pk=recipe_id).like()

    return redirect('Coffee:recipe', recipe_id=recipe_id)


def recipe_comment(request, recipe_id):
    if request.POST:
        form = CommentForm(request.POST)

        if form.is_valid():
            if not (pf.is_profane(form.cleaned_data['author']) or pf.is_profane(form.cleaned_data['comment'])):
                RecipeComment(recipe=get_object_or_404(Recipe, pk=recipe_id), author=form.cleaned_data['author'],
                              body=form.cleaned_data['comment']).save()

    return redirect('Coffee:recipe', recipe_id=recipe_id)


def written(request, written_id):
    w = get_object_or_404(WrittenPiece, pk=written_id)
    context = {'written': w, 'likeForm': CaptchaForm, 'commentForm': CommentForm,
               'comments_ordered': w.comments.all().order_by('-timestamp')}
    return render(request, 'Coffee/written_piece.html', context)


def written_home(request):
    written_list = WrittenPiece.objects.order_by('title')
    return render(request, 'Coffee/written_piece_home.html', {'written_list': written_list})


def written_like(request, written_id):
    if request.POST:
        form = CaptchaForm(request.POST)

        if form.is_valid():
            get_object_or_404(WrittenPiece, pk=written_id).like()

    return redirect('Coffee:writtenPiece', written_id=written_id)


def written_comment(request, written_id):
    if request.POST:
        form = CommentForm(request.POST)

        if form.is_valid():
            if not (pf.is_profane(form.cleaned_data['author']) or pf.is_profane(form.cleaned_data['comment'])):
                WrittenPieceComment(written_piece=get_object_or_404(WrittenPiece, pk=written_id),
                                    author=form.cleaned_data['author'],
                                    body=form.cleaned_data['comment']).save()

    return redirect('Coffee:writtenPiece', written_id=written_id)


def search(request):
    return render(request, 'Coffee/search.html', {'form': SearchForm()})


def search_result(request):
    if request.POST:
        form = SearchForm(request.POST)

        if form.is_valid():
            print(form.cleaned_data)
            if form.cleaned_data['type'] == 'w':
                written_list = WrittenPiece.objects.filter(
                    Q(title__contains=form.cleaned_data['text'].title()) |
                    Q(author__contains=form.cleaned_data['text'].title())
                )
                return render(request, 'Coffee/written_piece_home.html', {'written_list': written_list})
            elif form.cleaned_data['type'] == 'r':
                recipe_list = Recipe.objects.filter(
                    Q(title__contains=form.cleaned_data['text'].title()) |
                    Q(author__contains=form.cleaned_data['text'].title())
                )
                return render(request, 'Coffee/recipe_home.html', {'recipe_list': recipe_list})

    return redirect('Coffee:search')

templates/Coffee/recipe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

    <title>Coffee - Check Yo Self</title>

    <link rel="stylesheet" href="https://fuchsiaviciouskeygen.mitchelllong.repl.co/style.css">
</head>
<body>

{# Main nav for all pages #}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home' %}">Check Yo Self</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'Elements:index' %}">Elements</a>
        <a class="nav-item nav-link active" href="{% url 'Coffee:index' %}">Coffee</a>
        <a class="nav-item nav-link" href="{% url 'BallotMeasures:index' %}">Ballot Measures</a>
        <a class="nav-item nav-link" href="{% url 'Chemicals:index' %}">Controversial Chemicals</a>
    </div>
</nav>
<div class="p-4 extra-padding"></div>

<div class="row w-100">
    <div class="col">
        <a href="{% url 'Coffee:recipeHome' %}" class="btn btn-secondary float-left m-3 ml-5 mt-5">Go Back</a>
    </div>

    <div class="col-center">
        <ul class="nav nav-pills m-3 p-3 justify-content-center">
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:index' %}">Home</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link active" href="{% url 'Coffee:recipeHome' %}">Recipe</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:writtenPieceHome' %}">Written Pieces</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:search' %}">Search</a>
            </li>
        </ul>
    </div>
    <div class="col"></div>
</div>

<main class="mt-4 w-100">
    <div class="container text-center m-auto w-100">
        {# Title #}
        <div class="jumbotron p-2">
            <h1 class="display-3">{{ recipe.title }}</h1>
        </div>

        {# Image #}
        <img class="img-fluid rounded w-100" src="{{ recipe.image }}" alt="Recipe Image">


        <div class="m-auto">
            {# Author, Upvotes #}
            <div class="mt-2 bg-dark rounded">
                <div class="d-flex justify-content-center flex-wrap p-4">
                    <ul class="m-auto list-group">
                        <li class="list-group-item">{{ recipe.author }}</li>
                    </ul>
                    <div class="m-auto">
                        <p class="my-auto bg-success text-light d-inline-block rounded px-3 py-2">{{ recipe.likes }}
                            Upvotes</p>
                    </div>
                </div>
                <div class="mb-5 p-4">
                    {# Add Upvote #}
                    <form action="{% url 'Coffee:recipeLike' recipe.id %}" method="post" id="likeForm">
                        {% csrf_token %}
                        <div class="row mx-auto justify-content-center">
                            <div class="px-1 my-auto">
                                {{ likeForm.captcha }}
                            </div>
                            <div class="px-1 my-auto">
                                <input type="submit" value="Add Upvote" class="btn btn-success btn-sm">
                            </div>
                        </div>
                    </form>
                </div>

                {# Comments #}
                <h4 class="text-white">Comments</h4>
                <div class="rounded p-4 bg-dark">
                    <form action="{% url 'Coffee:recipeComment' recipe.id %}" method="post" id="commentForm">
                        {% csrf_token %}
                        <div class="form-item">
                            {{ commentForm.captcha }}
                        </div>
                        <div class="form-item">
                            <label for="author">Name: </label>
                            {{ commentForm.author }}
                        </div>
                        <div class="form-item">
                            <label for="author">Comment: </label>
                            {{ commentForm.comment }}
                        </div>
                        <div class="form-item">
                            <input type="submit" value="Add Comment" class="btn btn-success btn-sm">
                        </div>
                    </form>
                    <ul class="bg-light comments rounded">
                        {% for comment in comments_ordered %}
                            <li><b>{{ comment.author }}:</b> {{ comment.body }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</main>

{# Footer that goes on every page #}
<footer class="mt-5">
    <div class="container mt-5 mb-5">
        <a href="#" class="float-right"><p class="text-primary">Back To Top</p></a>
        <p class="m-3">Created by Mitchell L. and Scott S.</p>
        <p class="m-3">Created Using
            <a href="https://www.djangoproject.com/" target="_blank" class="d-inline">Django</a>
            and <a href="https://getbootstrap.com/" target="_blank" class="d-inline">Bootstrap</a>
        </p>
    </div>
</footer>

</body>
</html>

templates/Coffee/recipe_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="" name="description">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

    <title>Coffee - Check Yo Self</title>
    <link rel="stylesheet" href="https://fuchsiaviciouskeygen.mitchelllong.repl.co/style.css">
</head>
<body>

{# Main nav for all pages #}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home' %}">Check Yo Self</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'Elements:index' %}">Elements</a>
        <a class="nav-item nav-link active" href="{% url 'Coffee:index' %}">Coffee</a>
        <a class="nav-item nav-link" href="{% url 'BallotMeasures:index' %}">Ballot Measures</a>
        <a class="nav-item nav-link" href="{% url 'Chemicals:index' %}">Controversial Chemicals</a>
    </div>
</nav>
<div class="p-4 extra-padding"></div>

<div class="row w-100">
    <div class="col">
        <a href="{% url 'Coffee:index' %}" class="btn btn-secondary float-left m-3 ml-5 mt-5">Go Back</a>
    </div>

    <div class="col-center">
        <ul class="nav nav-pills m-3 p-3 justify-content-center">
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:index' %}">Home</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link active" href="{% url 'Coffee:recipeHome' %}">Recipe</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:writtenPieceHome' %}">Written Pieces</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:search' %}">Search</a>
            </li>
        </ul>
    </div>
    <div class="col"></div>
</div>

<main class="recipe-home">
    <div class="mx-4 row">
        {% for recipe in recipe_list %}
            <div class="m-auto">
                <div class="card shadow m-3">
                    <img src="{{ recipe.thumbnail }}" class="card-img-top img-fluid" alt="Recipe Photo"
                         style="max-width: 300px;">
                    <div class="card-body">
                        <h3 class="card-title text-center">{{ recipe.title }}</h3>
                        <h5 class="card-subtitle font-weight-light text-center">{{ recipe.author }}</h5>
                        <a href="{% url 'Coffee:recipe' recipe.id %}" class="btn btn-primary d-block mt-4">Read
                            More</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="m-auto">
            <div class="card shadow m-3">
                <img src="https://img.youtube.com/vi/ar_dS0ntuok/default.jpg" class="card-img-top img-fluid"
                     alt="Recipe Photo"
                     style="max-width: 300px;">
                <div class="card-body">
                    <h3 class="card-title text-center">Persian Tea</h3>
                    <h5 class="card-subtitle font-weight-light text-center">Armin B</h5>
                    <a target="_blank" href="https://www.youtube.com/watch?v=ar_dS0ntuok&feature=emb_logo"
                       class="btn btn-primary d-block mt-4">Read
                        More</a>
                </div>
            </div>
        </div>
    </div>
</main>

{# Footer that goes on every page #}
<footer class="mt-5">
    <div class="container mt-5 mb-5">
        <a href="#" class="float-right"><p class="text-primary">Back To Top</p></a>
        <p class="m-3">Created by Mitchell L. and Scott S.</p>
        <p class="m-3">Created Using
            <a href="https://www.djangoproject.com/" target="_blank" class="d-inline">Django</a>
            and <a href="https://getbootstrap.com/" target="_blank" class="d-inline">Bootstrap</a>
        </p>
    </div>
</footer>

</body>
</html>

templates/Coffee/search.html
<!DOCTYPE html>
<!--suppress JSUnresolvedLibraryURL -->
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="" name="description">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

    <title>Coffee - Check Yo Self</title>
    <link rel="stylesheet" href="https://fuchsiaviciouskeygen.mitchelllong.repl.co/style.css">
</head>
<body>

{# Main nav for all pages #}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home' %}">Check Yo Self</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'Elements:index' %}">Elements</a>
        <a class="nav-item nav-link active" href="{% url 'Coffee:index' %}">Coffee</a>
        <a class="nav-item nav-link" href="{% url 'BallotMeasures:index' %}">Ballot Measures</a>
        <a class="nav-item nav-link" href="{% url 'Chemicals:index' %}">Controversial Chemicals</a>
    </div>
</nav>
<div class="p-4 extra-padding"></div>

<div class="row w-100">
    <div class="col">
        <a href="{% url 'home' %}" class="btn btn-secondary float-left m-3 ml-5 mt-5">Home</a>
    </div>

    <div class="col-center">
        <ul class="nav nav-pills m-3 p-3 justify-content-center">
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:index' %}">Home</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:recipeHome' %}">Recipes</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:writtenPieceHome' %}">Written Pieces</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link active" href="{% url 'Coffee:search' %}">Search</a>
            </li>
        </ul>
    </div>
    <div class="col"></div>
</div>

<section class="jumbotron px-md-5 w-75 mx-auto my-3 shadow-sm bg-dark">
    <div class="row">
        <div class="col text-left">
            <h1 class="font-weight-light text-light">Search</h1>
        </div>
    </div>
    <form action="{% url 'Coffee:searchResult' %}" method="post" id="form" class="m-4">
        {% csrf_token %}
        <div>
            <div class="form-item">
                <label for="text">Term:</label>
                {{ form.text }}
            </div>
            <div class="form-item">
                <label for="text">Search By:</label>
                {{ form.type }}
            </div>
            <div class="row">
                <div class="col">
                    <input type="submit" value="Search" class="shadow btn btn-primary mt-3">
                </div>
            </div>
        </div>
    </form>
</section>

{# Footer that goes on every page #}
<footer class="mt-5">
    <div class="container mt-5 mb-5">
        <a href="#" class="float-right"><p class="text-primary">Back To Top</p></a>
        <p class="m-3">Created by Mitchell L. and Scott S.</p>
        <p class="m-3">Created Using
            <a href="https://www.djangoproject.com/" target="_blank" class="d-inline">Django</a>
            and <a href="https://getbootstrap.com/" target="_blank" class="d-inline">Bootstrap</a>
        </p>
    </div>
</footer>

</body>
</html>

templates/Coffee/written_piece.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

    <title>Coffee - Check Yo Self</title>

    <link rel="stylesheet" href="https://fuchsiaviciouskeygen.mitchelllong.repl.co/style.css">
</head>
<body>

{# Main nav for all pages #}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'home' %}">Check Yo Self</a>
        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-item nav-link" href="{% url 'Elements:index' %}">Elements</a>
        <a class="nav-item nav-link active" href="{% url 'Coffee:index' %}">Coffee</a>
        <a class="nav-item nav-link" href="{% url 'BallotMeasures:index' %}">Ballot Measures</a>
        <a class="nav-item nav-link" href="{% url 'Chemicals:index' %}">Controversial Chemicals</a>
    </div>
</nav>
<div class="p-4 extra-padding"></div>

<div class="row w-100">
    <div class="col">
        <a href="{% url 'Coffee:writtenPieceHome' %}" class="btn btn-secondary float-left m-3 ml-5 mt-5">Go Back</a>
    </div>

    <div class="col-center">
        <ul class="nav nav-pills m-3 p-3 justify-content-center">
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:index' %}">Home</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:recipeHome' %}">Recipe</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link active" href="{% url 'Coffee:writtenPieceHome' %}">Written Pieces</a>
            </li>
            <li class="nav-item px-1">
                <a class="nav-link" href="{% url 'Coffee:search' %}">Search</a>
            </li>
        </ul>
    </div>
    <div class="col"></div>
</div>

<main class="mt-4 w-100">
    <div class="container text-center m-auto w-100">
        {# Title #}
        <div class="jumbotron p-2">
            <h1 class="display-3">{{ written.title }}</h1>
        </div>

        {# Text #}
        <div class="m-2 mb-4 px-4 py-3 rounded text-left">
            {{ written.text|safe }}
        </div>

        {# Author, Upvotes #}
        <div class="m-auto">
            <div class="mt-2 bg-dark rounded">
                <div class="d-flex justify-content-center flex-wrap p-4">
                    <ul class="m-auto list-group">
                        <li class="list-group-item">{{ written.author }}</li>
                    </ul>
                    <div class="m-auto">
                        <p class="my-auto bg-success text-light d-inline-block rounded px-3 py-2">{{ written.likes }}
                            Upvotes</p>
                    </div>
                </div>
                <div class="mb-5 p-4">
                    {# Add Upvote #}
                    <form action="{% url 'Coffee:writtenPieceLike' written.id %}" method="post" id="likeForm">
                        {% csrf_token %}
                        <div class="row mx-auto justify-content-center">
                            <div class="px-1 my-auto">
                                {{ commentForm.captcha }}
                            </div>
                            <div class="px-1 my-auto">
                                <input type="submit" value="Add Upvote" class="btn btn-success btn-sm">
                            </div>
                        </div>
                    </form>
                </div>

                {# Comments #}
                <h4 class="text-white">Comments</h4>
                <div class="rounded p-4 bg-dark">
                    <form action="{% url 'Coffee:writtenPieceComment' written.id %}" method="post" id="commentForm">
                        {% csrf_token %}
                        <div class="form-item">
                            {{ commentForm.captcha }}
                        </div>
                        <div class="form-item">
                            <label for="author">Name: </label>
                            {{ commentForm.author }}
                        </div>
                        <div class="form-item">
                            <label for="author">Comment: </label>
                            {{ commentForm.comment }}
                        </div>
                        <div class="form-item">
                            <input type="submit" value="Add Comment" class="btn btn-success btn-sm">
                        </div>
                    </form>
                    <ul class="bg-light comments rounded">
                        {% for comment in comments_ordered %}
                            <li><b>{{ comment.author }}:</b> {{ comment.body }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</main>

{# Footer that goes on every page #}
<footer class="mt-5">
    <div class="container mt-5 mb-5">
        <a href="#" class="float-right"><p class="text-primary">Back To Top</p></a>
        <p class="m-3">Created by Mitchell L. and Scott S.</p>
        <p class="m-3">Created Using
            <a href="https://www.djangoproject.com/" target="_blank" class="d-inline">Django</a>
            and <a href="https://getbootstrap.com/" target="_blank" class="d-inline">Bootstrap</a>
        </p>
    </div>
</footer>

</body>
</html>